# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:
{ # List packages installed in system profile. To search, run:
  environment.systemPackages = with pkgs; [
    #### TERMINAL TOOLS

    zsh zsh-completions zsh-syntax-highlighting zsh-autosuggestions

    wget curl git ripgrep-all
    man-pages tmux

    ##### ncurses app
    htop w3m

    #### PRIVACY
    gopass gnupg


    #### DEVELOPEMENT

    stdenv gnumake binutils-unwrapped gnum4 gmp gmp6

    ##### Langage
    # C
    libev libudev libusb hidapi
     conf-perl
    gcc gdb  pkg-config

    # ocaml
    opam

    python pythonFull python3Full

    # python37Packages.gmpy2
        hidapi

        perl

        #sound
        ncpamixer

        #spelling
        # my-aspell

        ledger-live-desktop

  ];

  fonts = {
    enableFontDir = true;
    enableGhostscriptFonts = true;
    fonts = with pkgs; [
      liberation_ttf
      noto-fonts
    ];
  };

  # Select internationalisation properties.
  i18n = {
    consoleFont = "Lat2-Terminus16";
    consoleKeyMap = "fr";
    defaultLocale = "fr_FR.UTF-8";
  };

  # Set your time zone.
  time.timeZone = "Europe/Paris";

  # Sound.
  sound.enable = true;
  hardware.pulseaudio= {
    enable = true;
    package =pkgs.pulseaudioFull;
  };

  hardware.bluetooth.enable = true;
  # services.blueman.enable = true;

  services.pcscd.enable = true;

  services.udev.packages = [ pkgs.yubikey-personalization pkgs.libu2f-host ];

  environment.shellInit = ''
    	export GPG_TTY="$(tty)"
      gpg-connect-agent /bye
      export SSH_AUTH_SOCK="/run/user/$UID/gnupg/S.gpg-agent.ssh"
  '';

  programs = {
    zsh = {
      enable = true;
      enableCompletion = true;
      autosuggestions.enable = true;
    };
    browserpass.enable = true;
  };


}
